#!/usr/bin/env node
// Deliberately narrow, dependency-free bundler for the three reviewed ESM modules.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SCANNER_SHA256 } from '../host-gate.mjs';

const root=fileURLToPath(new URL('../',import.meta.url));
const modules=[
  {file:'host-gate.mjs',id:'__host',exports:['SCANNER_SHA256','GateError','scanManifest','createAttachmentGate']},
  {file:'review-override.mjs',id:'__review',exports:['createReviewPolicy']},
  {file:'stdio-wrapper.mjs',id:'__wrapper',exports:['JsonLines','startWrapper']},
];
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const read=name=>readFileSync(join(root,name),'utf8').replace(/\r\n?/g,'\n');

export function renderBundle() {
  const builtins=new Map(),bindings=new Map(),sources={},bodies=[];
  for(const mod of modules) {
    let source=read(mod.file);
    sources[mod.file]=hash(source);
    source=source.replace(/^#![^\n]*\n/,'');
    const localImports=[];
    source=source.replace(/^import\s*\{([^}]+)\}\s*from\s*(['"])([^'"]+)\2;\s*$/gm,(_,names,_quote,specifier)=>{
      const members=names.split(',').map(n=>n.trim());
      if(members.some(n=>!/^[$A-Z_a-z][$\w]*$/.test(n)))throw Error('Unsupported import syntax in '+mod.file);
      if(specifier.startsWith('node:')) {
        if(!builtins.has(specifier))builtins.set(specifier,new Set());
        for(const name of members) {
          if(bindings.has(name)&&bindings.get(name)!==specifier)throw Error('Conflicting builtin binding: '+name);
          bindings.set(name,specifier);builtins.get(specifier).add(name);
        }
      } else {
        const dependency=modules.find(m=>'./'+m.file===specifier);
        if(!dependency||modules.indexOf(dependency)>=modules.indexOf(mod))throw Error('Unsupported dependency: '+specifier);
        if(members.some(n=>!dependency.exports.includes(n)))throw Error('Unknown local export');
        localImports.push('const {'+members.join(',')+'}='+dependency.id+';');
      }
      return '';
    });
    const exports=[];
    source=source.replace(/^export\s+(?=(?:async\s+)?function\s+|class\s+|const\s+)(?:(async)\s+)?(function|class|const)\s+(\w+)/gm,(_,async,kind,name)=>{
      exports.push(name);return (async?'async ':'')+kind+' '+name;
    });
    if(JSON.stringify(exports.slice().sort())!==JSON.stringify(mod.exports.slice().sort()))throw Error('Export contract changed: '+mod.file);
    if(/^\s*(import\s|export\s)/m.test(source))throw Error('Unbundled module syntax: '+mod.file);
    if(mod.id==='__wrapper') {
      const before="new URL('./vendor/agent-scan.cjs',import.meta.url)";
      if(source.split(before).length!==2)throw Error('Scanner path contract changed');
      source=source.replace(before,"new URL('./agent-scan.cjs',import.meta.url)");
    }
    bodies.push('const '+mod.id+' = '+(mod.id==='__wrapper'?'await (async':'(')+' () => {\n'+localImports.join('\n')+'\n'+source+'\nreturn {'+mod.exports.join(',')+'};\n})();');
  }
  const imports=[...builtins].sort(([a],[b])=>a.localeCompare(b)).map(([specifier,names])=>'import {'+[...names].sort().join(',')+'} from '+JSON.stringify(specifier)+';').join('\n');
  const license=read('LICENSE.txt').trim().replace(/\*\//g,'* /');
  const bundle='#!/usr/bin/env node\n/* Agent Scan stdio gate. Generated by scripts/build-release.mjs.\n'+license+'\n*/\n'+imports+'\n'+bodies.join('\n')+'\nexport const {JsonLines,startWrapper}=__wrapper;\n';
  return {bundle,sources};
}

export function buildRelease(output=join(root,'dist')) {
  const scanner=readFileSync(join(root,'vendor/agent-scan.cjs'));
  if(hash(scanner)!==SCANNER_SHA256)throw Error('Vendor scanner digest mismatch');
  const {bundle,sources}=renderBundle();
  const filename='agent-scan-gate.mjs';
  const checksums={[filename]:hash(bundle),'agent-scan.cjs':hash(scanner)};
  mkdirSync(output,{recursive:true});
  writeFileSync(join(output,filename),bundle,{encoding:'utf8',mode:0o755});
  copyFileSync(join(root,'vendor/agent-scan.cjs'),join(output,'agent-scan.cjs'));
  for(const [name,digest] of Object.entries(checksums))writeFileSync(join(output,name+'.sha256'),digest+'  '+name+'\n');
  writeFileSync(join(output,'LICENSE.txt'),read('LICENSE.txt'));
  // A local build cannot assert publication. The tag identifies the intended
  // release; verify its existence and asset bytes independently on GitHub.
  writeFileSync(join(output,'build.json'),JSON.stringify({format:'backbond-host-gate-build/v1',wrapper_version:'0.1.0',scanner_version:'0.6.2',source_sha256:sources,sha256:checksums,runtime_dependencies:'Node.js built-ins only',release_tag:'host-gate-v0.1.0'},null,2)+'\n');
  return {output,checksums,sources};
}

if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)) {
  if(process.argv.length>3)throw Error('Usage: node scripts/build-release.mjs [output-directory]');
  process.stdout.write(JSON.stringify(buildRelease(process.argv[2]?resolve(process.argv[2]):undefined))+'\n');
}
